[package]
name = "gravity-sim"
version = "0.1.0"
authors = ["Bartłomiej Kamiński <fizyk20@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.7"
gio = "0.7"
numeric-algs = "0.2"
nalgebra = "0.18"
num = "*"
